M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date ned 05 mar 2023 21:16:24
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-05T21:16:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X101.6Y-45.72
X101.6Y-76.2
X177.8Y-45.72
X177.8Y-76.2
T0
M30
